###
#   Server port
###
server:
  port: 9000

###
#   Mail Settings
###

spring:
  ###
  #   Database Settings
  ###
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        use_sql_comments: true
        format_sql: true

  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: true


